[tool.ruff]
line-length = 200
target-version = "py310"
# fix = true

[tool.ruff.lint]
select = [
  # pycodestyle
  "E", "W",
  # flake8-2020
  "YTT",
  # flake8-bugbear
  "B",
  # flake8-quotes
#   "Q",
  # flake8-debugger
  "T10",
  # flake8-gettext
  "INT",
  # flake8-pytest-style
  "PT",
  # flake8-pyi
  "PYI",
  # flake8-type-checking
  "TC",
  # Ruff-specific rules
  "RUF",
  # flake8-bandit: exec-builtin
  "S102",
  # flake8-logging-format
  "G",
  # flake8-future-annotations
  "FA",
  # flake8-slots
  "SLOT",
  # flake8-raise
  "RSE"
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.coverage.run]
omit = [
    "src/__init__.py",
    "src/visualization_functions.py"
    ]

[tool.pytest.ini_options]
pythonpath = [
    ".",
    "src",
    "tests"
]
addopts = [
    "-v",
    "--cov=src",
    "--cov-branch",
    "--color=yes",
    "--cov-report=html",
]
markers = [
    "transforms: pre-processing with Kornia and tranformation of images",
    "dataset_functions: downloading and managing tree species files",
    "dataset: managing the entire dataset for the model efficiently",
    "callbacks: managing and monitoring learning process",
    "git_functions: managing commits to repo and wandb",
    "model: creating model for experiments"
]
filterwarnings = [
    "ignore:Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `pytorch_lightning` package.*",
]

[tool.mypy]
files = "src"
ignore_missing_imports = true
