dataset:
  folder: "src/data"
  species_folders:
    Abies_alba: "data/imagery-Abies_alba.zip"
    Abies_nordmanniana: "data/imagery-Abies_nordmanniana.zip"
    Castanea_sativa: "data/imagery-Castanea_sativa.zip"
    Fagus_sylvatica: "data/imagery-Fagus_sylvatica.zip"
    Larix_decidua: "data/imagery-Larix_decidua.zip"
    Picea_abies: "data/imagery-Picea_abies.zip"
    Pinus_halepensis: "data/imagery-Pinus_halepensis.zip"
    Pinus_nigra: "data/imagery-Pinus_nigra.zip"
    Pinus_nigra_laricio: "data/imagery-Pinus_nigra_laricio.zip"
    Pinus_pinaster: "data/imagery-Pinus_pinaster.zip"
    Pinus_sylvestris: "data/imagery-Pinus_sylvestris.zip"
    Pseudotsuga_menziesii: "data/imagery-Pseudotsuga_menziesii.zip"
    Quercus_ilex: "data/imagery-Quercus_ilex.zip"
    Quercus_petraea: "data/imagery-Quercus_petraea.zip"
    Quercus_pubescens: "data/imagery-Quercus_pubescens.zip"
    Quercus_robur: "data/imagery-Quercus_robur.zip"
    Quercus_rubra: "data/imagery-Quercus_rubra.zip"
    Robinia_pseudoacacia: "data/imagery-Robinia_pseudoacacia.zip"
  main_subfolders:
    aerial_imagery: "imagery/"
    lidar: "lidar/"

model: 
  name: "resnet18" # currently supporting resnet18, vit and inception_v3

training:
  batch_size: 32
  learning_rate: 0.00003
  max_epochs: 100
  freeze: true
  weight_decay: 0.0001
  
  oversample:
    oversample_factor: 4
    oversample_threshold: 1000
  # undersample:
  #   target_size: 530

  # curriculum_learning:
  #   initial_ratio: 2
  #   step_size: 1
  #   class_order: [10, 11, 5, 7, 9, 1, 12, 0, 2, 3, 6, 4, 8] # Based on decreasing IoU 

  # class_weights: [2.028603482052949,
  #                 1.9149570077824503,
  #                 2.3698711832307096,
  #                 2.7918140711618267,
  #                 8.404431999123624,
  #                 1.4891439907690158,
  #                 2.8278190246173205,
  #                 1.559603179364982,
  #                 8.968666793195208,
  #                 1.750924051756126,
  #                 1.4114322619818822,
  #                 1.4826886210799306,
  #                 2.025711256102825] # Weights calculated using log2((1/IoU)+1)
  
  dataloader:
    auto: true
    num_workers: 0
    pin_memory: false
    presistent_workers: false

  early_stopping:
    apply: true
    monitor: "val_loss"
    patience: 3
    mode: "min"

device: "gpu"
