name: CPU - Train Model, push logs to Wandb

on:
    workflow_dispatch:

jobs:
    build:
        permissions: write-all
        runs-on: ubuntu-latest
        environment: Repository

        steps:
            -   uses: actions/checkout@v3

            -   uses: actions/setup-node@v3
                with:
                    node-version: '16'

            -   uses: actions/setup-python@v5
                with:
                    python-version: '3.11.11'
                    cache: 'pip'

            -   uses: iterative/setup-cml@v1

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r unix-requirements.txt

            -   name: Set WANDB API key
                run: |
                    echo "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" >> $GITHUB_ENV

            -   name: Run Python script
                run: python src/main.py

            -   name: Post plots with CML in PR comment
                env:
                    REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    echo "## Model was built using Config" >> config.md
                    sed 's/  /\&nbsp;/g' ./src/config.yaml > config-indented.md
                    echo "## Data viz" >> config-indented.md
                    echo '![](./src/plots/confusion_matrix.png "Confusion Matrix")' >> config-indented.md
                    cml comment update --watermark-title='CPU {workflow} config' config-indented.md
