name: Linting & Formatting Check

on:
    pull_request:

permissions:
    contents: read

jobs:
    ruff:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: astral-sh/ruff-action@v3
                with:
                    version-file: "my-path/to/pyproject.toml-or-requirements.txt"

            -   name: Run Ruff lint check
                run: ruff check

            -   name: Run Ruff format check
                run: ruff format --check
