name: Tests and Coverage Deployment

on:
    pull_request:
    workflow_dispatch:
        

permissions:
    contents: read
    pages: write
    id-token: write

jobs:

    pytest:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest ]
                python-version: [ '3.10' ]

        steps:
            -   uses: actions/checkout@v6
            -   name: Install uv
                uses: astral-sh/setup-uv@v5
                with:
                    enable-cache: true
            -   name: Set up Python ${{ matrix.python-version }}
                run: uv python install ${{ matrix.python-version }}
            -   name: Run tests
                run: uv run pytest

    deploy-coverage-page:
        runs-on: ubuntu-latest
        concurrency:
                group: 'pages'
                cancel-in-progress: true
        steps:
            -   uses: actions/checkout@v6
            -   uses: actions/configure-pages@v5
            -   name: Install uv
                uses: astral-sh/setup-uv@v5
                with:
                    enable-cache: true
            -   name: Set up Python
                run: uv python install 3.10
            -   name: Generate test coverage
                run: uv run pytest --cov=src --cov-report=html
            -   name: Upload artifacts
                uses: actions/upload-pages-artifact@v4
                with:
                    path: htmlcov
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4
